language: ruby
rvm:
  - 2.1
  - 2.2.4
  - 2.3.0
  - ruby-head
before_install:
  - sudo apt-get install libxslt-dev libxml2-dev
  - gem install bundler
before_script:
  - cp test/config.yml.default test/config.yml
only:
  - master
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: always
