language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
before_install:
  - sudo apt-get install libxslt-dev libxml2-dev
before_script:
  - cp test/config.yml.default test/config.yml
only:
  - master
notifications:
  email: false
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
